name: christmas-obfuscated-c
summary: Christmas Obfuscated C programs
description: These programs are the collection of Colin Ian King's Christmas themed Obfuscated C programs from https://github.com/ColinIanKing/christmas-obfuscated-C
confinement: strict
grade: stable
assumes: [snapd2.45]
base: core18
adopt-info: christmas-obfuscated-c

parts:
    christmas-obfuscated-c:
        plugin: make
        source: git://github.com/ColinIanKing/christmas-obfuscated-c
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"

        stage-packages:
            - libtinfo-dev
        build-packages:
            - gcc
            - make
            - libncurses-dev
            - libncursesw5-dev
            - libgmp3-dev
            - libtinfo-dev

apps:
    christmas-2012:
        command: christmas-2012
    koch-binary:
        command: koch-binary
    snowman:
        command: snowman
    tupper:
        command: tupper
    snow:
        command: snow
    happy-christmas:
        command: happy-christmas
    snowman2019:
        command: snowman2019
